requires 'Pod::POM';
requires 'PPI';
requires 'PPI::XS';
requires 'MooseX::DBIC';
requires 'Catalyst::View::JavaScript';
requires 'Catalyst::View::TT::Alloy';
requires 'Catalyst::View::JSON';
requires 'SQL::Translator'; # not really, but for now
requires 'CatalystX::RoleApplicator';
requires 'Catalyst::Model::DBIC::Schema';
requires 'CPAN::Meta';
requires 'Syntax::Highlight::Engine::Kate';
requires 'CatalystX::ExtJS' => '1.101560';